=== lmiceli/FlickrApp/sample/generated-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://id.net",
  "type": "object",
  "properties": {
    "title": {
      "id": "title",
      "type": "string"
    },
    "link": {
      "id": "link",
      "type": "string"
    },
    "description": {
      "id": "description",
      "type": "string"
    },
    "modified": {
      "id": "modified",
      "type": "string"
    },
    "generator": {
      "id": "generator",
      "type": "string"
    },
    "items": {
      "id": "items",
      "type": "array",
      "items": [
        {
          "id": "items",
          "type": "object",
          "properties": {
            "title": {
              "id": "items/title",
              "type": "string"
            },
            "link": {
              "id": "items/link",
              "type": "string"
            },
            "media": {
              "id": "items/media",
              "type": "object",
              "properties": {
                "m": {
                  "id": "items/media/m",
                  "type": "string"
                }
              }
            },
            "date_taken": {
              "id": "items/date_taken",
              "type": "string"
            },
            "description": {
              "id": "items/description",
              "type": "string"
            },
            "published": {
              "id": "items/published",
              "type": "string"
            },
            "author": {
              "id": "items/author",
              "type": "string"
            },
            "author_id": {
              "id": "items/author_id",
              "type": "string"
            },
            "tags": {
              "id": "items/tags",
              "type": "string"
            }
          }
        }
      ]
    }
  },
  "required": [
    "title",
    "link",
    "description",
    "modified",
    "generator",
    "items"
  ]
}

=== lmiceli/FlickrApp/sample/data.json
{
  "title": "Uploads from everyone",
  "link": "https://www.flickr.com/photos/",
  "description": "",
  "modified": "2016-03-31T00:49:04Z",
  "generator": "https://www.flickr.com/",
  "items": [{
    "title": "234A2761.jpg",
    "link": "https://www.flickr.com/photos/wcdumonts/25538291494/",
    "media": {
      "m": "https://farm2.staticflickr.com/1485/25538291494_c1961c5ed1_m.jpg"
    },
    "date_taken": "2016-03-26T09:57:04-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/wcdumonts/\">Mark Dumont<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/wcdumonts/25538291494/\" title=\"234A2761.jpg\"><img src=\"https://farm2.staticflickr.com/1485/25538291494_c1961c5ed1_m.jpg\" width=\"160\" height=\"240\" alt=\"234A2761.jpg\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:04Z",
    "author": "nobody@flickr.com (Mark Dumont)",
    "author_id": "23661161@N02",
    "tags": "animals mammal zoo mark cincinnati takin dumont"
  }, {
    "title": "Ipanema/30.03.16 Foto: Ellan Lustosa",
    "link": "https://www.flickr.com/photos/ellanlustosa/25538292634/",
    "media": {
      "m": "https://farm2.staticflickr.com/1449/25538292634_48213e37b8_m.jpg"
    },
    "date_taken": "2016-03-30T17:49:10-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/ellanlustosa/\">elanlustosa<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/ellanlustosa/25538292634/\" title=\"Ipanema/30.03.16 Foto: Ellan Lustosa\"><img src=\"https://farm2.staticflickr.com/1449/25538292634_48213e37b8_m.jpg\" width=\"240\" height=\"160\" alt=\"Ipanema/30.03.16 Foto: Ellan Lustosa\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:10Z",
    "author": "nobody@flickr.com (elanlustosa)",
    "author_id": "100411277@N04",
    "tags": "square squareformat iphoneography instagramapp uploaded:by=instagram"
  }, {
    "title": "Northwood Panthers Track vs. Mishawaka and Riley-2.jpg",
    "link": "https://www.flickr.com/photos/jpk3031/25540420083/",
    "media": {
      "m": "https://farm2.staticflickr.com/1687/25540420083_9f9889eee6_m.jpg"
    },
    "date_taken": "2016-03-29T16:05:01-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/jpk3031/\">JeffKnight45<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/jpk3031/25540420083/\" title=\"Northwood Panthers Track vs. Mishawaka and Riley-2.jpg\"><img src=\"https://farm2.staticflickr.com/1687/25540420083_9f9889eee6_m.jpg\" width=\"160\" height=\"240\" alt=\"Northwood Panthers Track vs. Mishawaka and Riley-2.jpg\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:07Z",
    "author": "nobody@flickr.com (JeffKnight45)",
    "author_id": "38721563@N07",
    "tags": ""
  }, {
    "title": "IMG_20160315_192051352",
    "link": "https://www.flickr.com/photos/129418129@N03/25540421133/",
    "media": {
      "m": "https://farm2.staticflickr.com/1635/25540421133_89fccd01ae_m.jpg"
    },
    "date_taken": "2016-03-15T19:20:52-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/129418129@N03/\">mikebertino90<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/129418129@N03/25540421133/\" title=\"IMG_20160315_192051352\"><img src=\"https://farm2.staticflickr.com/1635/25540421133_89fccd01ae_m.jpg\" width=\"240\" height=\"135\" alt=\"IMG_20160315_192051352\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:13Z",
    "author": "nobody@flickr.com (mikebertino90)",
    "author_id": "129418129@N03",
    "tags": ""
  }, {
    "title": " ",
    "link": "https://www.flickr.com/photos/boeing777cat/25870196420/",
    "media": {
      "m": "https://farm2.staticflickr.com/1598/25870196420_5d17391998_m.jpg"
    },
    "date_taken": "2016-03-30T22:00:38-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/boeing777cat/\">Xing chasing the light<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/boeing777cat/25870196420/\" title=\" \"><img src=\"https://farm2.staticflickr.com/1598/25870196420_5d17391998_m.jpg\" width=\"180\" height=\"240\" alt=\" \" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:08Z",
    "author": "nobody@flickr.com (Xing chasing the light)",
    "author_id": "46830706@N05",
    "tags": ""
  }, {
    "title": "Garage 1",
    "link": "https://www.flickr.com/photos/smlombardi/25870196920/",
    "media": {
      "m": "https://farm2.staticflickr.com/1448/25870196920_7bd2e45f24_m.jpg"
    },
    "date_taken": "2016-03-30T16:25:15-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/smlombardi/\">smLombardi<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/smlombardi/25870196920/\" title=\"Garage 1\"><img src=\"https://farm2.staticflickr.com/1448/25870196920_7bd2e45f24_m.jpg\" width=\"240\" height=\"240\" alt=\"Garage 1\" /><\/a><\/p> <p>Processed with VSCO with a9 preset<\/p>",
    "published": "2016-03-31T00:49:10Z",
    "author": "nobody@flickr.com (smLombardi)",
    "author_id": "29135749@N06",
    "tags": ""
  }, {
    "title": "_DSF2630.jpg",
    "link": "https://www.flickr.com/photos/ianchamberlain/25870197190/",
    "media": {
      "m": "https://farm2.staticflickr.com/1514/25870197190_004bca70dd_m.jpg"
    },
    "date_taken": "2016-03-20T15:49:11-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/ianchamberlain/\">Ian Chamberlain1<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/ianchamberlain/25870197190/\" title=\"_DSF2630.jpg\"><img src=\"https://farm2.staticflickr.com/1514/25870197190_004bca70dd_m.jpg\" width=\"240\" height=\"160\" alt=\"_DSF2630.jpg\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:11Z",
    "author": "nobody@flickr.com (Ian Chamberlain1)",
    "author_id": "54590494@N06",
    "tags": "4 motocross amca galecommon"
  }, {
    "title": "DSC_7152lr",
    "link": "https://www.flickr.com/photos/megalev/26050579772/",
    "media": {
      "m": "https://farm2.staticflickr.com/1565/26050579772_c73c02d575_m.jpg"
    },
    "date_taken": "2015-09-24T11:00:10-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/megalev/\">Uberlev<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/megalev/26050579772/\" title=\"DSC_7152lr\"><img src=\"https://farm2.staticflickr.com/1565/26050579772_c73c02d575_m.jpg\" width=\"240\" height=\"172\" alt=\"DSC_7152lr\" /><\/a><\/p> <p>Swanage<\/p>",
    "published": "2016-03-31T00:49:04Z",
    "author": "nobody@flickr.com (Uberlev)",
    "author_id": "47001186@N05",
    "tags": "swanage"
  }, {
    "title": "Last nights #sunset",
    "link": "https://www.flickr.com/photos/adrants/26050580252/",
    "media": {
      "m": "https://farm2.staticflickr.com/1606/26050580252_6188866507_m.jpg"
    },
    "date_taken": "2016-03-30T20:49:06-08:00",
    "description": "<p><a href=\"https://www.flickr.com/people/adrants/\">adrants<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/adrants/26050580252/\" title=\"Last nights #sunset\"><img src=\"https://farm2.staticflickr.com/1606/26050580252_6188866507_m.jpg\" width=\"240\" height=\"240\" alt=\"Last nights #sunset\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:06Z",
    "author": "nobody@flickr.com (adrants)",
    "author_id": "93461622@N00",
    "tags": "square squareformat iphoneography instagramapp uploaded:by=instagram foursquare:venue=4a334835f964a520259b1fe3"
  }, {
    "title": "“Photographic industry” push to the social photographic task.",
    "link": "https://www.flickr.com/photos/50144379@N03/26050580302/",
    "media": {
      "m": "https://farm2.staticflickr.com/1531/26050580302_e414b40133_m.jpg"
    },
    "date_taken": "2016-03-30T18:49:07-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/50144379@N03/\">instante distante<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/50144379@N03/26050580302/\" title=\"“Photographic industry” push to the social photographic task.\"><img src=\"https://farm2.staticflickr.com/1531/26050580302_e414b40133_m.jpg\" width=\"192\" height=\"240\" alt=\"“Photographic industry” push to the social photographic task.\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:07Z",
    "author": "nobody@flickr.com (instante distante)",
    "author_id": "50144379@N03",
    "tags": "square squareformat iphoneography instagramapp uploaded:by=instagram"
  }, {
    "title": "拍攝中 Sakura Photographer #japan #cityview #instajapan #japansakura #Sakura #flowers #photographer #sakuratree #新宿 #新宿御苑",
    "link": "https://www.flickr.com/photos/jaffera/26050580642/",
    "media": {
      "m": "https://farm2.staticflickr.com/1623/26050580642_6b4e59a002_m.jpg"
    },
    "date_taken": "2016-03-31T08:49:08-08:00",
    "description": " <p><a href=\"https://www.flickr.com/people/jaffera/\">jaffera<\/a> posted a photo:<\/p> <p><a href=\"https://www.flickr.com/photos/jaffera/26050580642/\" title=\"拍攝中 Sakura Photographer #japan #cityview #instajapan #japansakura #Sakura #flowers #photographer #sakuratree #新宿 #新宿御苑\"><img src=\"https://farm2.staticflickr.com/1623/26050580642_6b4e59a002_m.jpg\" width=\"240\" height=\"205\" alt=\"拍攝中 Sakura Photographer #japan #cityview #instajapan #japansakura #Sakura #flowers #photographer #sakuratree #新宿 #新宿御苑\" /><\/a><\/p> ",
    "published": "2016-03-31T00:49:08Z",
    "author": "nobody@flickr.com (jaffera)",
    "author_id": "30282152@N06",
    "tags": "square squareformat ludwig iphoneography instagramapp uploaded:by=instagram"
  }, {
    "title": "DE5_0430_ADJ_ADJ",
    "link": "https://www.flickr.com/photos/takkotakko/26076719061/",
    "media": {
      "m": "https://farm2.staticflickr.com/1452/26076719061_a68efbfca0_m.jpg"
    },
    "date_taken": "2016-03-30T10:44:09-08:00",
